---
title: "Reproduction of Paper: SARS-CoV-2 restructures host chromatin architecture"
author: "Xiaohan Xie, Daven Lim, Louis Meller"
date: last-modified
toc: true
number-sections: true
format:
  pdf:
    code-line-numbers: false
    code-overflow: wrap
    geometry:
      - top=30mm
      - left=30mm
    include-in-header:
      - text: |
          \usepackage{pdfpages}
---

## Introduction

In this project, we aim to re-analyze and reproduce parts of the paper “SARS-CoV-2 restructures host chromatin architecture” by Wang, R., Lee, J. H., Kim, J. et al., published in Nature Microbiology in 2023.
SARS-CoV-2, the virus responsible for COVID-19, caused a global pandemic and has been widely studied for its effects. However, it is relatively unknown whether SARS-CoV-2 could alter the 3D organization of the host genome. Chromatin architecture plays a critical role in regulating gene expression by controlling how different regions of the genome interact, and changes to chromatin organization can have widespread effects on cellular function and host response to infection. The original study aims to characterize the 3D genome and epigenome of human cells after SARS-CoV-2 infection, where they find widespread host chromatin restructuring and show that SARS-CoV-2 disrupts chromatin organization.
As COVID-19 remains one of the most significant public health events in recent history, we chose this study to apply the methods introduced in class to a biologically relevant problem. In our analyses, we focus on three key aspects of chromatin organization: altered topologically associating domain (TAD) contacts, changes in chromatin compartmentalization (A/B compartments), and loop extrusion. By reproducing these analyses, we evaluate whether our results support the authors' conclusion that SARS-CoV-2 infection causes large-scale restructuring of host chromatin architecture.

```{=latex}
\addcontentsline{toc}{subsection}{2.1 Part 1: AB Compartment Analyses}
\includepdf[pages=-]{AB_compartment_analyses/AB_compartment_analyses.pdf}
```

```{=latex}
\addcontentsline{toc}{subsection}{2.2 Part 2: TAD Analyses}
\includepdf[pages=-]{part2_tad/covid_project_tad_pdf.pdf}
```

```{=latex}
\addcontentsline{toc}{subsection}{2.3 Part 3: Chromatin Loop Analyses}
\includepdf[pages=-]{loop_calling/loop_analysis4.pdf}
```
